name: CI

on:
  push:
    branches:
      - master
      - '*'
    tags:
      - '*'
  pull_request:
  schedule:
    # Weekly Tuesday 9:05 PM build
    - cron: "5 21 * * 2"

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.9 Tests Ubuntu
            python-version: '3.9'
            os: ubuntu-latest
            toxenv: py39

          - name: Python 3.9 Tests MacOs 11
            os: macos-11
            python-version: '3.9'
            toxenv: py39

          - name: Python 3.9 Tests MacOs 12
            os: macos-12
            python-version: '3.9'
            toxenv: py39

          - name: Python 3.8 Tests Ubuntu
            python-version: '3.8'
            os: ubuntu-latest
            toxenv: py38

          - name: Python 3.8 Tests MacOs 11
            os: macos-11
            python-version: '3.8'
            toxenv: py38

          - name: Python 3.8 Tests MacOs 12
            os: macos-12
            python-version: '3.8'
            toxenv: py38

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: |
          pip install tox

      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}
